name: Build Windows EXE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build EXE
        run: pyinstaller --onefile --name snake main.py
      
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: snake-build
          path: dist/snake.exe

      - name: Create GitHub Release
        id: snake_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/snake.exe
          tag_name: "v0.0.1"
          body: |
            Snake release!
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
